name: Unit Tests
on: [push, pull_request]

jobs:
  node_matrix:
    uses: appium/appium-workflows/.github/workflows/node-lts-matrix.yml@main

  test:
    runs-on: ubuntu-latest
    needs:
    - node_matrix
    strategy:
      matrix:
        node-version: ${{ fromJSON(needs.node_matrix.outputs.versions) }}
    steps:
      - uses: actions/checkout@v7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
      - uses: SocketDev/action@v1
        with:
          mode: firewall-free
      - name: Install dev dependencies
        run: sfw npm install --no-package-lock
      - name: Run linter
        run: npm run lint
      - run: npm run format:check
        name: Run format check
      - name: Run unit tests
        run: npm run test
